name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!

on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Ejecutar programa
        run: |
          dotnet new console -n HolaApp
          mv hola-mundo.cs HolaApp/Program.cs
          cd HolaApp
          dotnet run
